# Generated by Django 2.2.4 on 2019-08-16 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('time', models.TimeField(auto_created=True, verbose_name='时间')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('descript', models.CharField(max_length=200, verbose_name='简介')),
                ('name', models.CharField(max_length=20, verbose_name='文章名字')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.User', verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.Article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '文章喜欢表',
                'verbose_name_plural': '文章喜欢表',
                'db_table': 'article_like',
            },
        ),
    ]
